title:             Hodongman의 개발 블로그
email:             jhd9206@gmail.com
description:       연구한거 기록용
author:            hodongman
baseurl:           "/"
url:               "https://hodongman.github.io"

# Social Profiles
twitter_username:  hodongman
github_username:   hodongman
facebook_username: hodongman

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
