title:             Hodongman 의 개발 블로그
email:             jhd9206@gmail.com
description:       웹, 프론트엔드, 벡엔드, 개발, 언어, 알고리즘, 자료구조, 게임, 모바일, 인공지능, 빅데이터, 머신러닝, 딥러닝
author:            hodongman
baseurl:           "/"
url:               "https://hodongman.github.io"

# Social Profiles
twitter_username:  hodongman
github_username:   hodongman
facebook_username: hodongman

# Build settings
markdown:          kramdown
paginate:          10
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
